#**********************************************
#	This file was automatically generated 2024:09:20T13:04:00
#	
#	DO NOT EDIT THIS FILE -- Use Dialog Builder Tools to edit this file.
#***********************************************

import vs

# control IDs
kOK                   = 1
kCancel               = 2
kUnnamed1             = 4
kleftButton           = 5
krightButton          = 6
kcenterButton         = 7

def CreateDialog():
    # Alignment constants
    kRight                = 1
    kBottom               = 2
    kLeft                 = 3
    kColumn               = 4
    kResize               = 0
    kShift                = 1

    def GetPluginString(ndx):
        # Static Text
        if ndx == 1001:			return 'OK'
        elif ndx == 1002:		return 'Cancel'
        elif ndx == 1003:		return 'Choose Photometrics Direction'
        elif ndx == 1004:		return 'Which direction is the light coming from?'
        elif ndx == 1005:		return 'Left'
        elif ndx == 1006:		return 'Right'
        elif ndx == 1007:		return 'Top'
        # Help Text
        elif ndx == 2001:		return 'Accepts the dialog data.'
        elif ndx == 2002:		return 'Cancels the dialog data.'
        elif ndx == 2004:		return 'Help text.'
        elif ndx == 2005:		return 'Help text.'
        elif ndx == 2006:		return 'Help text.'
        elif ndx == 2007:		return 'Help text.'
        return ''

    def GetStr(ndx):
        result = GetPluginString( ndx + 1000 )
        return result

    def GetHelpStr(ndx):
        result = GetPluginString( ndx + 2000 )
        return result

    dialog = vs.CreateLayout( GetStr(3), False, GetStr(kOK), GetStr(kCancel) )

    # create controls
    vs.CreateStaticText( dialog, kUnnamed1, GetStr(kUnnamed1), -1 )
    vs.CreateRadioButton( dialog, kleftButton, GetStr(kleftButton) )
    vs.CreateRadioButton( dialog, krightButton, GetStr(krightButton) )
    vs.CreateRadioButton( dialog, kcenterButton, GetStr(kcenterButton) )

    # set relations
    vs.SetFirstLayoutItem( dialog, kUnnamed1 )
    vs.SetBelowItem( dialog, kUnnamed1, kleftButton, 0, 0 )
    vs.SetRightItem( dialog, kleftButton, krightButton, 0, 0 )
    vs.SetRightItem( dialog, krightButton, kcenterButton, 0, 0 )

    # set alignments

    # set help strings
    cnt = 1
    while ( cnt <= 7 ):
        vs.SetHelpText( dialog, cnt, GetHelpStr(cnt) )
        cnt += 1

    return dialog

# Sample dialog handler
# Uncomment this code if you want to display the dialog
'''
def DialogHandler(item, data):
	pass

Vectorworks_Photometrics = CreateDialog()
vs.RunLayoutDialog( Vectorworks_Photometrics, DialogHandler )
'''

# XML defintion of the layout
#
# <BEGIN_XML>
#<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
# <DialogBuilder>
# 
#   <LayoutData>
#     <Name>Vectorworks_Photometrics</Name>
#     <Title>Choose Photometrics Direction</Title>
#     <OKText>OK</OKText>
#     <OKHelpText>Accepts the dialog data.</OKHelpText>
#     <CancelText>Cancel</CancelText>
#     <CancelHelpText>Cancels the dialog data.</CancelHelpText>
#     <HasHelp>False</HasHelp>
#     <ResizableWidth>False</ResizableWidth>
#     <ResizableHeight>False</ResizableHeight>
#     <StringsStartID>0</StringsStartID>
#     <HelpStrStartID>1</HelpStrStartID>
#     <TablesAddToDlgRes>True</TablesAddToDlgRes>
#     <AltStringStartID>0</AltStringStartID>
#     <ResourceRoot>PluginModule_resource_file_vwr</ResourceRoot>
#   </LayoutData>
# 
#   <Controls>
#     <Control name="DialogBuilderControl" x="0" y="-15">
#       <Parameter Name="__UUID">{E77F2D2B-3E27-432B-8B1D-B31DF491F6F4}</Parameter>
#       <Parameter Name="type">kRadioButton</Parameter>
#       <Parameter Name="id">5</Parameter>
#       <Parameter Name="constName">leftButton</Parameter>
#       <Parameter Name="label">Left</Parameter>
#       <Parameter Name="helpText">Help text.</Parameter>
#       <Parameter Name="bindLeft">kNone</Parameter>
#       <Parameter Name="bindRight">kNone</Parameter>
#       <Parameter Name="bindTop">kNone</Parameter>
#       <Parameter Name="bindBottom">kNone</Parameter>
#       <Parameter Name="realEditType"></Parameter>
#       <Parameter Name="renderMode">Wireframe</Parameter>
#       <Parameter Name="viewMode">Top/Plan</Parameter>
#       <Parameter Name="hasFrame">True</Parameter>
#       <Parameter Name="ControlPoint00X">26mm</Parameter>
#       <Parameter Name="ControlPoint00Y">-3mm</Parameter>
#       <Parameter Name="ControlPoint01X">17mm</Parameter>
#       <Parameter Name="ControlPoint01Y">-15mm</Parameter>
#       <Parameter Name="ControlPoint02X">0mm</Parameter>
#       <Parameter Name="ControlPoint02Y">0mm</Parameter>
#       <Parameter Name="__RightUUID">{EF6CC218-F375-4627-B992-F8073143D721}</Parameter>
#       <Parameter Name="__BottomUUID">{1A308F6E-F521-4298-AC6A-2E59562F31CC}</Parameter>
#       <Parameter Name="__savedHandleRightX">26mm</Parameter>
#       <Parameter Name="__savedHandleRightY">-3mm</Parameter>
#       <Parameter Name="__savedHandleBottomX">17mm</Parameter>
#       <Parameter Name="__savedHandleBottomY">-15mm</Parameter>
#       <Parameter Name="__fVisControlWidth">16</Parameter>
#       <Parameter Name="__fVisControlHeight">5</Parameter>
#       <Parameter Name="extPopupShowIcons">True</Parameter>
#     </Control>
#     <Control name="DialogBuilderControl" x="0" y="0">
#       <Parameter Name="__UUID">{50C9AB13-3172-4671-891D-489F88E9193D}</Parameter>
#       <Parameter Name="id">4</Parameter>
#       <Parameter Name="constName">Unnamed1</Parameter>
#       <Parameter Name="label">Which direction is the light coming from?</Parameter>
#       <Parameter Name="helpText">Help text.</Parameter>
#       <Parameter Name="bindLeft">kNone</Parameter>
#       <Parameter Name="bindRight">kNone</Parameter>
#       <Parameter Name="bindTop">kNone</Parameter>
#       <Parameter Name="bindBottom">kNone</Parameter>
#       <Parameter Name="realEditType"></Parameter>
#       <Parameter Name="renderMode">Wireframe</Parameter>
#       <Parameter Name="viewMode">Top/Plan</Parameter>
#       <Parameter Name="hasFrame">True</Parameter>
#       <Parameter Name="ControlPoint00X">82mm</Parameter>
#       <Parameter Name="ControlPoint00Y">-2mm</Parameter>
#       <Parameter Name="ControlPoint01X">8mm</Parameter>
#       <Parameter Name="ControlPoint01Y">-15mm</Parameter>
#       <Parameter Name="ControlPoint02X">0mm</Parameter>
#       <Parameter Name="ControlPoint02Y">0mm</Parameter>
#       <Parameter Name="__BottomUUID">{E77F2D2B-3E27-432B-8B1D-B31DF491F6F4}</Parameter>
#       <Parameter Name="__savedHandleRightX">82mm</Parameter>
#       <Parameter Name="__savedHandleRightY">-2mm</Parameter>
#       <Parameter Name="__savedHandleBottomX">8mm</Parameter>
#       <Parameter Name="__savedHandleBottomY">-15mm</Parameter>
#       <Parameter Name="__fVisControlWidth">82</Parameter>
#       <Parameter Name="__fVisControlHeight">5</Parameter>
#       <Parameter Name="extPopupShowIcons">True</Parameter>
#     </Control>
#     <Control name="DialogBuilderControl" x="26" y="-15">
#       <Parameter Name="__UUID">{EF6CC218-F375-4627-B992-F8073143D721}</Parameter>
#       <Parameter Name="type">kRadioButton</Parameter>
#       <Parameter Name="id">6</Parameter>
#       <Parameter Name="constName">rightButton</Parameter>
#       <Parameter Name="label">Right</Parameter>
#       <Parameter Name="helpText">Help text.</Parameter>
#       <Parameter Name="bindLeft">kNone</Parameter>
#       <Parameter Name="bindRight">kNone</Parameter>
#       <Parameter Name="bindTop">kNone</Parameter>
#       <Parameter Name="bindBottom">kNone</Parameter>
#       <Parameter Name="realEditType"></Parameter>
#       <Parameter Name="renderMode">Wireframe</Parameter>
#       <Parameter Name="viewMode">Top/Plan</Parameter>
#       <Parameter Name="hasFrame">True</Parameter>
#       <Parameter Name="ControlPoint00X">29mm</Parameter>
#       <Parameter Name="ControlPoint00Y">-3mm</Parameter>
#       <Parameter Name="ControlPoint01X">9mm</Parameter>
#       <Parameter Name="ControlPoint01Y">-5mm</Parameter>
#       <Parameter Name="ControlPoint02X">0mm</Parameter>
#       <Parameter Name="ControlPoint02Y">0mm</Parameter>
#       <Parameter Name="__RightUUID">{BD944380-B2CC-4930-9196-AF64E85A6972}</Parameter>
#       <Parameter Name="__savedHandleRightX">29mm</Parameter>
#       <Parameter Name="__savedHandleRightY">-3mm</Parameter>
#       <Parameter Name="__savedHandleBottomX">9mm</Parameter>
#       <Parameter Name="__savedHandleBottomY">-5mm</Parameter>
#       <Parameter Name="__fVisControlWidth">19</Parameter>
#       <Parameter Name="__fVisControlHeight">5</Parameter>
#       <Parameter Name="extPopupShowIcons">True</Parameter>
#     </Control>
#     <Control name="DialogBuilderControl" x="55" y="-15">
#       <Parameter Name="__UUID">{BD944380-B2CC-4930-9196-AF64E85A6972}</Parameter>
#       <Parameter Name="type">kRadioButton</Parameter>
#       <Parameter Name="id">7</Parameter>
#       <Parameter Name="constName">centerButton</Parameter>
#       <Parameter Name="label">Top</Parameter>
#       <Parameter Name="helpText">Help text.</Parameter>
#       <Parameter Name="bindLeft">kNone</Parameter>
#       <Parameter Name="bindRight">kNone</Parameter>
#       <Parameter Name="bindTop">kNone</Parameter>
#       <Parameter Name="bindBottom">kNone</Parameter>
#       <Parameter Name="realEditType"></Parameter>
#       <Parameter Name="renderMode">Wireframe</Parameter>
#       <Parameter Name="viewMode">Top/Plan</Parameter>
#       <Parameter Name="hasFrame">True</Parameter>
#       <Parameter Name="ControlPoint00X">16mm</Parameter>
#       <Parameter Name="ControlPoint00Y">-2mm</Parameter>
#       <Parameter Name="ControlPoint01X">8mm</Parameter>
#       <Parameter Name="ControlPoint01Y">-5mm</Parameter>
#       <Parameter Name="ControlPoint02X">0mm</Parameter>
#       <Parameter Name="ControlPoint02Y">0mm</Parameter>
#       <Parameter Name="__savedHandleRightX">16mm</Parameter>
#       <Parameter Name="__savedHandleRightY">-2mm</Parameter>
#       <Parameter Name="__savedHandleBottomX">8mm</Parameter>
#       <Parameter Name="__savedHandleBottomY">-5mm</Parameter>
#       <Parameter Name="__fVisControlWidth">16</Parameter>
#       <Parameter Name="__fVisControlHeight">5</Parameter>
#       <Parameter Name="extPopupShowIcons">True</Parameter>
#     </Control>
#     <Control name="Dialog Builder Link" x="0" y="0">
#       <Parameter Name="ParentObj">{50C9AB13-3172-4671-891D-489F88E9193D}</Parameter>
#       <Parameter Name="RelatedObj">{E77F2D2B-3E27-432B-8B1D-B31DF491F6F4}</Parameter>
#       <Parameter Name="ParentMode">1</Parameter>
#     </Control>
#     <Control name="Dialog Builder Link" x="0" y="0">
#       <Parameter Name="ParentObj">{E77F2D2B-3E27-432B-8B1D-B31DF491F6F4}</Parameter>
#       <Parameter Name="RelatedObj">{EF6CC218-F375-4627-B992-F8073143D721}</Parameter>
#       <Parameter Name="ParentMode">0</Parameter>
#     </Control>
#     <Control name="Dialog Builder Link" x="0" y="0">
#       <Parameter Name="ParentObj">{EF6CC218-F375-4627-B992-F8073143D721}</Parameter>
#       <Parameter Name="RelatedObj">{BD944380-B2CC-4930-9196-AF64E85A6972}</Parameter>
#       <Parameter Name="ParentMode">0</Parameter>
#     </Control>
#   </Controls>
# 
# </DialogBuilder>
# 
# <END_XML>

